[package]
name = "itzmrratsp/genericstatemachine"
version = "0.2.41"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
    "selene.toml",
    ".gitignore",
    "README.md",
    "sourcemap.json",
    "roblox.yml",
    "rokit.toml",
    # "wally.toml",
]

[dependencies]
#empty dependencies
